### PR TITLE
Allow passing kwargs to backends for advanced initialization needs

### PR DESCRIPTION
**Pull request by davidovich**
This PR allows more advanced backend configuration. In my use case, I needed to use swift authentication version 2, which needs additionnal parameters at backend initialization time:

i.e. 

```
storage = fs.Storage('myfs',
                    fs.ARCHIVES + fs.DATA,
                    auth_version='2',
                    tenant_name='my_tenant')

fs.init_app(app, storage)
```

### CODE REVIEW

**Comment by davidovich** [comment]
I understand that this PR departs from the configuration only stance. I am open to a better, more abstract implementation route. For instance, my proposed PR does not allow testing on two variations of the swift backend since the kwargs are hard coded at storage creation time.

It should be possible to amend the config keys to allow a generic _KWARGS based config which would contain a dictionary.

@noirbizarre Any thoughts ?

**Comment by noirbizarre** [comment]
I like the idea but yes there is place for improvement (and testing :wink: ).
I think the generic `_KWARGS` on config is the right way to go. As it will be a dictionnary, to preserve cascading like other parameters, this config should have a special treatment ie. performing an `update()` from `__init__` parameters then from config parameters to allow proper overriding from configuration.

Do you think you can implement that (and test it a little bit so I won't break it in the future) ?

**Comment by davidovich** [comment]
Yes, I will implement the generic dictionary. In fact, I think we should allow any parameters to be constructed and passed to the backend connector.

Below is what I have in mind:

1. Contruct a mapping using backend keys and _key suffix. For example:

   FS_SWIFT_auth_version='2'  # note that keys have to be same-cased as the param
   FS_SWIFT_tenant_name='my_tenant'
   
Note however that this idea does not go far enough, as the kwargs could eventually collide with the present implementation that binds to fixes parameters (in swift.py: config.user, config.key, config.authurl)

So, we could transfer to a backend config subkey: config.swift which would receive all params to be passed to the connector:

2. Construct complete mapping of connector construction and put it at the backend key:

    FS_SWIFT_user='...'
    FS_SWIFT_key='...'
    FS_SWIFT_authurl='...'
    FS_SWIFT_auth_version='2' # we might fall into a case where the value should be an integer, which we could safely parse using [ast.literal_eval()](https://docs.python.org/3/library/ast.html#ast.literal_eval) for simple cases
    FS_SWIFT_tenant_name='...'

    This will construct a config.swift object containing all the suffix keys

    Internal usage would be like so:

    swiftclient.Connection(**config.swift)

**Comment by davidovich** [comment]
* Note that s3 is a bit particular because there is a translation of key names provided to the s3 connector:

    `endpoint` maps to `endpoint_url`
    `region` maps to `region_name`

and so on:
```
        self.s3 = self.session.resource('s3',
                                        config=self.s3config,
                                        endpoint_url=config.s3.endpoint,
                                        region_name=config.s3.region,
                                        aws_access_key_id=config.s3.access_key,
                                        aws_secret_access_key=config.s3.secret_key)
```
Having the same key name would allow a uniform usage:
```
self.s3 = self.session.resource('s3', config=self.s3config, **config.s3)
```

* MongoClient has similar translation (from `mongo_url` to `host` (first parameter to the MongoClient connector class))

But this changes compatibility. I will implement a conversion function in specified backends.

**Comment by noirbizarre** [comment]
I'll release what's already on the master and I'm working on some refinements on your implementation to perform another release.

I started from your branch, and what I'm currently doing is:
- treat any not excluded parameter as backend kwarg (ie. `FS_SWIFT_XXX` will automatically bind to `xxx`)
- raise deprecation warnings when deprecated parameters are found (ie. tune your `_convert_legacy_config` which allows to properly handle forward/backward compatibility, I like that)
- consistency on casing (Flask parameters are upper case)
- optionnal dict support for `FS_{BACKEND}_KWARGS` which will be applied last

Are you OK with that ?

**Pull request closed without merging**
